apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dis.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dis.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dis.name" . }}
    spec:
      serviceAccountName: {{ include "dis.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: MESSAGE_QUEUE_ENDPOINT
              value: {{ .Values.env.messageQueueEndpoint | quote }}
            - name: PORT
              value: "8001"
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelay }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelay }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}