replicaCount: 2

image:
  repository: 659591640509.dkr.ecr.us-west-2.amazonaws.com/cloudopshub-das
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

serviceAccount:
  create: true
  name: "cloudopshub-das-sa"

secrets:
  dbPassword: "prod-db-password-here"
  apiKey: "das-internal-key"

env:
  dataStoreUrl: "http://cloudopshub-aps:5000"

probes:
  livenessPath: /health
  readinessPath: /ready
  initialDelay: 10
  period: 20

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi