apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "das.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "das.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "das.name" . }}
    spec:
      serviceAccountName: {{ include "das.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: PORT
              value: "8000"
            - name: DATA_STORE_URL
              value: {{ .Values.env.dataStoreUrl | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "das.fullname" . }}-auth
                  key: DATABASE_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ include "das.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelay }}
            periodSeconds: {{ .Values.probes.period }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelay }}
            periodSeconds: {{ .Values.probes.period }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}