replicaCount: 2

image:
  repository: 659591640509.dkr.ecr.us-west-2.amazonaws.com/cloudopshub-dis
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001

serviceAccount:
  create: true
  name: "cloudopshub-dis-sa"

# Queue Configuration
env:
  messageQueueEndpoint: "kafka-broker.messaging.svc.cluster.local:9092"

probes:
  livenessPath: /health
  readinessPath: /ready
  initialDelay: 10
  period: 20

resources:
  limits:
    cpu: 300m
    memory: 512Mi # Increased for background task overhead
  requests:
    cpu: 150m
    memory: 256Mi