apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . }}-nginx-config
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Zero-Debug Proxy: Points to the DAS service name
        location /api/ {
            proxy_pass http://{{ .Release.Name }}-das:80/;
            proxy_set_header Host $host;
        }
    }